---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-deployment
  labels:
    app: kubernetes-spring
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-spring
      tier: frontend
  template:
    metadata:
      labels:
        app: kubernetes-spring
        tier: frontend
    spec:
      containers:
      - name: kub-demo
        image: gcr.io/fir-check-fdbf8/kubernetes-demo:v1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: kub-deployment
  labels:
    app: kubernetes-spring
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kubernetes-spring
    tier: frontend

---
